version: '3.8'

services:

  nginx:
    container_name: 'plapper_nginx'
    build: .
    ports:
      - '9100:80'
    restart: unless-stopped

  soketi:
    container_name: 'plapper_soketi'
    image: quay.io/soketi/soketi:1.6-16-distroless
    ports:
      - '9110:6001'
    environment:
      SOKETI_DEBUG: '${SOKETI_DEBUG}'
      SOKETI_DEFAULT_APP_KEY: '${SOKETI_DEFAULT_APP_KEY}'
      SOKETI_DEFAULT_APP_ID: '${SOKETI_DEFAULT_APP_ID}'
      SOKETI_DEFAULT_APP_SECRET: '${SOKETI_DEFAULT_APP_SECRET}'
      SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: '${SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES}'
    restart: unless-stopped
